name: Docker Image CI / CD
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/${{ github.repository }}/doctoc:latest
    # - name: Docker login
    #   run: echo $GITHUB_TOKEN | docker login docker.pkg.github.com --username ${{github.actor}} --password-stdin
    # - name: Push Docker image to Github package registry
    #   run: docker push docker.pkg.github.com/${{ github.repository }}/doctoc:latest
    - name:  Push Docker image to Github package registry
      run: |
        echo ${{ secrets.GITHUB_REGISTRY_TOKEN }} | docker login docker.pkg.github.com --username ${{github.actor}} --password-stdin
        docker push docker.pkg.github.com/${{ github.repository }}/doctoc:latest
      # env:
      #   GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
    - name: Logout
      run: docker logout
...
